apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kubernetespoc
  labels:
    app: kubernetespoc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetespoc
  template:
    metadata:
      labels:
        app: kubernetespoc
    spec:
      containers:
      - name: kubernetespoc
        image: derage/kubernetespoc:5
        resources:
          requests:
            memory: "5Gi"
            cpu: "250m"
        ports:
        - name: kpoc-port
          containerPort: 3000
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 80
        #     httpHeaders:
        #     - name: X-Custom-Header
        #       value: Awesome
        #   initialDelaySeconds: 3
        #   periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 3
